rancher:
  hosts:
    sprl-dev-rancher01.office-devel:
      kernel_version: 4.4.0.187.193

docker-registry:
  hosts:
    sprl-registry01.office-devel:
      kernel_version: 4.4.0.187.193

kubernetes:
  hosts:
    # Kubernetesのマスタノード
    sprl-dev-kubemaster01.office-devel:
      rancher_agent_ip: 172.16.205.69 
      kubernetes_type: master
      kernel_version: 4.4.0.187.193
    sprl-dev-kubemaster02.office-devel:
      rancher_agent_ip: 172.16.205.70
      kubernetes_type: master
      kernel_version: 4.4.0.187.193
    sprl-dev-kubemaster03.office-devel:
      rancher_agent_ip: 172.16.205.87
      kubernetes_type: master
      kernel_version: 4.4.0.187.193

    # Kubernetesのコンピュートノード
    sprl-dev-kubenode01.office-devel:
      rancher_agent_ip: 172.16.205.71 
      kubernetes_type: node
      kernel_version: 4.4.0.187.193
    sprl-dev-kubenode02.office-devel:
      rancher_agent_ip: 172.16.205.88
      kubernetes_type: node
      kernel_version: 4.4.0.187.193
    sprl-dev-kubenode03.office-devel:
      rancher_agent_ip: 172.16.205.89
      kubernetes_type: node
      kernel_version: 4.4.0.187.193

kafka_servers:
  hosts:
    10.22.0.13:
      kafka_broker_id: 1
    10.22.0.12:
      kafka_broker_id: 2
    10.22.0.11:
      kafka_broker_id: 3

zk_servers:
  hosts:
    10.22.0.13:
      zookeeper_id: 1
    10.22.0.12:
      zookeeper_id: 2
    10.22.0.11:
      zookeeper_id: 3


redis:
  hosts:
    10.22.0.13:
    10.22.0.12:
    10.22.0.11:

db:
  hosts:
    # マスタ
    sprl-dev-db01.office-devel:
      db_roles: [account, spiral, node, kong, email, dns, cms, account_node]

#    # スレーブ
#    sprl-dev-db02.office-devel:
#      db_roles: []

    # マスタ
    sprl-dev-db03.office-devel:
      db_roles: [node]
    # スレーブ
    sprl-dev-db04.office-devel:
      db_roles: []

    # マスタ
    sprl-dev-db05.office-devel:
      db_roles: [node]
    # スレーブ
    sprl-dev-db06.office-devel:
      db_roles: []

# 開発結合環境では、userdbは使用しない
#    sprl-dev-userdb01.office-devel:
#      db_roles: [node] 

custom-postfix:
  hosts:
    # smtp_helo_name: 送信側postfixに付与したglobal fqdnを記入する. 本来は各custom-postfixのipに対応する固有の値を設定する.
    #                 devは環境の都合でrcv-dev.spiral-platform.netがメール送信の終端になっているため詐称中.
    #                 実際のところメールがinternel側に出る境界はrcv-dev.spiral-platform.netになっているため, この設定は効果が無い.
    sprl-dev-postfix01.office-devel: {smtp_helo_name: rcv-dev.spiral-platform.net}
    sprl-dev-postfix02.office-devel: {smtp_helo_name: rcv-dev.spiral-platform.net}
#    sprl-dev-postfix03.office-devel: {smtp_helo_name: rcv-dev.spiral-platform.net}
#    sprl-dev-postfix04.office-devel: {smtp_helo_name: rcv-dev.spiral-platform.net}

bounce-parser:
  hosts:
    sprl-dev-bounce-parser01.office-devel:
    sprl-dev-bounce-parser02.office-devel:

bounce-postfix:
  hosts:
    sprl-dev-haproxy01.office-devel:

web:
  hosts:
    sprl-dev-web01.office-devel:
      upstream_elasticsearch_host: sprl-dev-log01.office-devel
    sprl-dev-web02.office-devel:
      upstream_elasticsearch_host: sprl-dev-log02.office-devel

load-balancer:
  hosts:
    sprl-dev-haproxy01.office-devel:
       keepalived_role: MASTER
       keepalived_priority: 110
       letsencrypt_enabled: yes

log:
  hosts:
    sprl-dev-log01.office-devel:
      fluentd_enabled: true
    sprl-dev-log02.office-devel:
      fluentd_enabled: true
    sprl-dev-log03.office-devel:
      node_data: false

ceph:
  hosts:
    sprl-dev-ceph01.office-devel:
      monitor_address: "172.16.204.113"
      devices:
        - /dev/sdb
    sprl-dev-ceph02.office-devel:
      monitor_address: "172.16.204.114"
      devices:
        - /dev/sdb
    sprl-dev-ceph03.office-devel:
      monitor_address: "172.16.204.115"
      devices:
        - /dev/sdb

mongodb:
  hosts:
    10.22.0.13: # mongodb ansibleの初回実行時を除き, mongodb['hosts'][0] にはmongodb ansibleを実行済みのhostを記述してください.
    10.22.0.12:
    10.22.0.11:
    
activemq:
  hosts:
    10.22.0.13:
    10.22.0.12:
    10.22.0.11:

# XXX: allが空になる不具合に対応するため明示的にallを追加
all:
  vars:
    ansible_user=spiral
    ansible_ssh_pass=spiral
