- name: The first play
  hosts: kafka_servers
  become: true
  remote_user: spiral
  tasks:
    - name: remove kafka
      ansible.builtin.file:
        path: "/usr/local/kafka_2.13-2.7.0"
        state: absent
      